### ISSUE TITLE
Error in running code

### ISSUE THREAD

**Issue by uniqueLL** [arthurbra/citation-recommendation-kg#1]
Hi，Hello, I made this error in the running times：

def rank_documents(out_name, testset, all_docs, all_docs_vectors, dense_embeddings=False, write_ranking=False, like_specter=like_specter):
NameError: name 'like_specter' is not defined

at this position in the file citation-recommendation-kg-main.py：

def rank_documents(out_name, testset, all_docs, all_docs_vectors, dense_embeddings=False, write_ranking=False, like_specter=like_specter):
    avp10s = []
    avp20s = []
    avp50s = []
    avpAlls = []

I would appreciate it if you could give me some advice

**Comment by arthurbrack** [comment]
Thank you for the issue. I have removed the legacy code so it should now run.
